name: 'Copy ENV secrets'
description: 'Create .env file and copy environment secrets (including database connection info)'

runs:
  env:
    db_user: ${{ secrets.DB_USERNAME }}
    db_pass: ${{ secrets.DB_PASSWORD }}
  steps:
    - run: |
        touch server/.env
        echo DB_USERNAME="$db_user" >> server/.env
        echo DB_PASSWORD="$db_pass" >> server/.env
