on:
  push:
    branches:
    - ENV-action

name: Docker_Compose_Azure_Workflow
env:
    db_user: ${{ secrets.DB_USERNAME }}
    db_pass: ${{ secrets.DB_PASSWORD }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
         
    - run: |
            touch server/.env
            echo DB_USERNAME="$db_user" >> server/.env
            echo DB_PASSWORD="$db_pass" >> server/.env
      
    - uses: azure/docker-login@v1
      with:
        login-server: chutesandladders.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
            
    - run: |
        docker build ./client -t chutesandladders.azurecr.io/pipes:frontend
        docker push chutesandladders.azurecr.io/pipes:frontend
        
    - run: |
        docker build ./server -t chutesandladders.azurecr.io/pipes:backend
        docker push chutesandladders.azurecr.io/pipes:backend 
