on:
  push:
    branches:
    - ENV-action

name: Docker_Compose_Azure_Workflow
env:
    db_user: ${{ secrets.COSMOSDB_USER }}
    db_pass: ${{ secrets.COSMOSDB_PASSWORD }}
    db_name: ${{ secrets.COSMOSDB_NAME }}
    db_host: ${{ secrets.COSMOSDB_HOST }}
    db_port: ${{ secrets.COSMOSDB_PORT }}
    db_string: ${{ secrets.COSMOSDB_CONNECTION_STRING }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
         
    - run: |
            touch server/.env
            echo COSMOSDB_USER="$db_user" >> server/.env
            echo COSMOSDB_PASSWORD="$db_pass" >> server/.env
            echo COSMOSDB_DBNAME="$db_name" >> server/.env
            echo COSMOSDB_HOST="$db_host" >> server/.env
            echo COSMOSDB_PORT="$db_port" >> server/.env
            echo COSMOSDB_CONNECTION_STRING="$db_string" >> server/.env
            cat server/.env
      
    - uses: azure/docker-login@v1
      with:
        login-server: chutesandladders.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
            
    - run: |
        docker build ./client -t chutesandladders.azurecr.io/pipes:frontend
        docker push chutesandladders.azurecr.io/pipes:frontend
        
    - run: |
        docker build ./server -t chutesandladders.azurecr.io/pipes:backend
        docker push chutesandladders.azurecr.io/pipes:backend 
