on:
  push:
    branches:
    - master

name: Docker_Compose_Azure_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: chutesandladders.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build ./client -t chutesandladders.azurecr.io/pipes:frontend
        docker push chutesandladders.azurecr.io/pipes:frontend
        
    - run: |
        docker build ./server -t chutesandladders.azurecr.io/pipes:backend
        docker push chutesandladders.azurecr.io/pipes:backend 
